language: c++
compiler:
  - gcc
  - clang

dist: xenial

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - libcrypto++-dev
      - libboost-dev
      - librocksdb-dev

script:
  - export CC=gcc-8
  - export CXX=g++-8

