language: c++
compiler:
  - gcc

dist: xenial

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - libboost-dev
      - librocksdb-dev
      - libsecp256k1-dev

install:
# Travis CI uses Xenial, so we need to build Crypto++ ourselves
  - wget 'https://www.cryptopp.com/cryptopp810.zip'
  - unzip cryptopp810.zip -d cryptopp
  - pushd cryptopp
  - make
  - sudo make install
  - popd

script:
  - export CC=gcc-8
  - export CXX=g++-8
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest -V

