language: c++
compiler:
  - gcc

dist: xenial

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - libboost-dev
      - librocksdb-dev

install:
  - # Travis CI uses Xenial, so we need to build Crypto++ ourselves
  - wget 'https://www.cryptopp.com/cryptopp565.zip'
  - unzip cryptopp565.zip -d cryptopp
  - pushd cryptopp
  - make
  - sudo make install PREFIX=/usr
  - popd
  - sudo ln -s /usr/include/cryptopp /usr/include/crypto++
  - sudo ln -s /usr/lib/libcryptopp.a /usr/lib/libcrypto++.a

script:
  - export CC=gcc-8
  - export CXX=g++-8
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest -V

